# Generated by Django 4.1.7 on 2023-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(default='', max_length=13),
        ),
    ]
